# Generated by Django 4.2.7 on 2024-01-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Customer Name')),
                ('customer_address', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Address')),
                ('landmark', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Landmark')),
                ('phone', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('comment_order', models.TextField(blank=True, default='', max_length=3000, null=True, verbose_name='Comment')),
                ('media_file', models.FileField(blank=True, upload_to='PDFInvoice/')),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Invoicemngt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField(blank=True, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Customer Name')),
                ('product_one', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Product 1')),
                ('quantity_of_product_one', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('unit_price_of_product_one', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price')),
                ('total_price_of_product_one', models.IntegerField(blank=True, default=0, null=True, verbose_name='Total')),
                ('product_two', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Product 2')),
                ('quantity_of_product_two', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('unit_price_of_product_two', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price')),
                ('total_price_of_product_two', models.IntegerField(blank=True, default=0, null=True, verbose_name='Total')),
                ('product_three', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Product 3')),
                ('quantity_of_product_three', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('unit_price_of_product_three', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price')),
                ('total_price_of_product_three', models.IntegerField(blank=True, default=0, null=True, verbose_name='Total')),
                ('product_four', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Product 4')),
                ('quantity_of_product_four', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('unit_price_of_product_four', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price')),
                ('total_price_of_product_four', models.IntegerField(blank=True, default=0, null=True, verbose_name='Total')),
                ('product_five', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Product 5')),
                ('quantity_of_product_five', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('unit_price_of_product_five', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price')),
                ('total_price_of_product_five', models.IntegerField(blank=True, default=0, null=True, verbose_name='Total')),
                ('product_six', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Product 6')),
                ('quantity_of_product_six', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('unit_price_of_product_six', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price')),
                ('total_price_of_product_six', models.IntegerField(blank=True, default=0, null=True, verbose_name='Total')),
                ('product_seven', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Product 7')),
                ('quantity_of_product_seven', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('unit_price_of_product_seven', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price')),
                ('total_price_of_product_seven', models.IntegerField(blank=True, default=0, null=True, verbose_name='Total')),
                ('product_eight', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Product 8')),
                ('quantity_of_product_eight', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('unit_price_of_product_eight', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price')),
                ('total_price_of_product_eight', models.IntegerField(blank=True, default=0, null=True, verbose_name='Total')),
                ('product_nine', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Product 9')),
                ('quantity_of_product_nine', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('unit_price_of_product_nine', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price')),
                ('total_price_of_product_nine', models.IntegerField(blank=True, default=0, null=True, verbose_name='Total')),
                ('product_ten', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Product 10')),
                ('quantity_of_product_ten', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('unit_price_of_product_ten', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price')),
                ('total_price_of_product_ten', models.IntegerField(blank=True, default=0, null=True, verbose_name='Total')),
                ('phone_number', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('total', models.IntegerField(blank=True, default='0', null=True)),
                ('balance', models.IntegerField(blank=True, default='0', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True, default='', max_length=3000, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('invoice_type', models.CharField(blank=True, choices=[('Receipt', 'Receipt'), ('Invoice', 'Invoice')], default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Customer Name')),
                ('product_name', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Product Name')),
                ('order_number', models.IntegerField(blank=True, default=0, null=True, verbose_name='Order Number')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_referral', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Referral Name')),
                ('referral_code', models.IntegerField(blank=True, verbose_name='Code')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120)),
                ('product_price', models.FloatField(default=0)),
                ('product_unit', models.CharField(max_length=120)),
                ('product_is_delete', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(related_name='Products', to='mngtinvoice.product')),
            ],
        ),
    ]
